### ISSUE TITLE
Can't list tables - errors in Lambda

### ISSUE THREAD

**Issue by CloudySnake** [awslabs/amazon-athena-cross-account-catalog#5]
I'll prefix this by saying that it's entirely possible this is a problem of my own making.  I've followed the guide to the letter (using the cloudformation yaml provided) and whilst I can now run Athena queries across accounts I'm not able to list the tables in each database.  When I try I see the following errors logged in then cross account lambda

`Calling listTables({'dbName': '<my db name>', 'filter': None, 'nextToken': None, 'maxSize': -1})

[ERROR] KeyError: 'SerializationLibrary'
Traceback (most recent call last):
  File "/var/task/heracles/lambda.py", line 42, in handler
    result = klas().execute(api_request)
  File "/var/task/heracles/handlers/getters.py", line 107, in execute
    hive_table = HiveMappers.map_glue_table(databaseName, table['Name'], table)
  File "/var/task/heracles/handlers/hive_mappers.py", line 81, in map_glue_table
    serializationLib=glue_table['StorageDescriptor']['SerdeInfo']['SerializationLibrary'],`

I'm continuing to dig, but any advice would be much appreciated.

**Comment by CloudySnake** [comment]
I've seen there's a recent pull request that seems to cover this issue, so I'm thinking the zip version of the function in target might be out of date. Will check

**Comment by sajjanbh** [comment]
From the exception, it indicates that the requested table doesn't have attribute "StorageDescriptor->SerdeInfo-SerializationLibrary". It represents the SerDe information for the table.

In case of View, this field isn't present as only the base table contains it. So, it is normal for this exception to occur when requesting a View. However, as you mentioned, this part was fixed in the PR3.

That being said, if this error is occurring for an external table, could you check the table definition? Perhaps it was created in Hive without specifying SerDe? For this, you can use GetTable API (aws glue get-table command in AWS CLI). If you share this JSON here, I can also take a look.

For well defined tables/views, the tables should be correctly listed in console. You could also try running "SHOW TABLES" query.

**Comment by CloudySnake** [comment]
`{
  "Table": {
    "Name": "base_base",
    "DatabaseName": "",
    "Owner": "owner",
    "CreateTime": "2020-06-04T10:26:00+01:00",
    "UpdateTime": "2020-06-04T10:26:00+01:00",
    "LastAccessTime": "2020-06-04T10:26:00+01:00",
    "Retention": 0,
    "StorageDescriptor": {
      "Columns": [],
      "Location": "",
      "Compressed": true,
      "NumberOfBuckets": -1,
      "SerdeInfo": {
        "Parameters": {}
      },
      "BucketColumns": [],
      "SortColumns": [],
      "Parameters": {
        "CrawlerSchemaDeserializerVersion": "1.0",
        "CrawlerSchemaSerializerVersion": "1.0",
        "UPDATED_BY_CRAWLER": "",
        "classification": "UNKNOWN",
        "compressionType": "unknown",
        "objectCount": "1",
        "typeOfData": "file"
      },
      "StoredAsSubDirectories": false
    },
    "PartitionKeys": [],
    "TableType": "EXTERNAL_TABLE",
    "Parameters": {
      "CrawlerSchemaDeserializerVersion": "1.0",
      "CrawlerSchemaSerializerVersion": "1.0",
      "UPDATED_BY_CRAWLER": "c",
      "classification": "UNKNOWN",
      "compressionType": "unknown",
      "objectCount": "1",
      "typeOfData": "file"
    },
    "CreatedBy": "",
    "IsRegisteredWithLakeFormation": false,
    "CatalogId": ""
  }
}`

You are correct, it's missing the SerDe.  It appears that lots of our tables are missing this, though a lot of these tables aren't things we use (there's a lot of junk floating around the data lake at the moment).  They are almost all created by crawlers if that makes a difference?

I'm going to try tweaking the Lambda to not error at this point, just to see what happens.  I'm guessing trying to run a query on these 'bad' tables probably won't be possible. But like I said I don't think that's going to cause me an issue.

**Comment by sajjanbh** [comment]
Currently, the code doesn't correctly set the SerDe info if it isn't available in table definition. It could be addressed by replacing:
`serdeInfo=ttypes.SerDeInfo(
                serializationLib=glue_table['StorageDescriptor']['SerdeInfo']['SerializationLibrary'],
                parameters=glue_table['StorageDescriptor']['SerdeInfo']['Parameters'],
            )`
with:
`serdeInfo=ttypes.SerDeInfo(
                serializationLib=glue_table['StorageDescriptor'].get('SerdeInfo', {}).get('SerializationLibrary', ''),
                parameters=glue_table['StorageDescriptor'].get('SerdeInfo', {}).get('Parameters', {}),
            )`

in heracles/handlers/hive_mappers.py (within map_glue_table function and sd variable).

Yes, querying such tables will likely fail in lack of SerDe info.

**Comment by CloudySnake** [comment]
Thanks for your help.  I think I should be good from here.

**Comment by CloudySnake** [comment]
Dodgy data causing problems, will tweak my copy of the Lambda to work around them.

**Comment by sajjanbh** [comment]
You're welcome!
I've updated it in my fork, will create a PR later. If you've fixed it, you're welcome to do so.
https://github.com/sajjanbh/amazon-athena-cross-account-catalog/blob/master/heracles/handlers/hive_mappers.py#L107

BTW, you could configure Crawler to use exclude file patterns to prevent creation of unwanted tables or clutter.
