### ISSUE TITLE
Releases and published build artifacts

### ISSUE THREAD

**Issue by dmcguire81** [awslabs/amazon-athena-cross-account-catalog#6]
Are there any plans to start using GitHub Releases or a public Package Index to publish this code? We're currently consuming it and using it, unmodified, so there isn't any need for it to be under version control in our system. The only reason that the source even needs to be available is to repackage for lambda, so a GitHub Release that includes the lambda-packaged code as an artifact would be ideal, because that's a public resource we could consume into our build pipeline, directly.

Thanks!

**Comment by dmcguire81** [comment]
@aperiodic FYI

**Comment by dacort** [comment]
@dmcguire81 Wanted to check back in here - I'm the original author of this project and recently returned to AWS. 

Is this still something you're interested in? The project is intended to be a reference architecture, but happy to at least publish a usable release.

**Comment by dmcguire81** [comment]
@dacort thanks for checking in - we've already got a solution in place, but I'm sure other consumers would appreciate built artifacts.

**Comment by carsten-bo** [comment]
I added a Dockerfile that can be used for dockerized Lambdas and also easily be distributed as an artifact. I would be interested in your opinion on that. @dacort 

PR: #12

**Comment by dacort** [comment]
@carsten-bo Thanks, that's pretty helpful! I added a couple comments on that PR.

**Comment by dacort** [comment]
FYI, Athena just announced official support for connecting to a Glue Data Catalog in another account:

https://docs.aws.amazon.com/athena/latest/ug/data-sources-glue-cross-account.html

I'll likely be archiving this repository, but feel free to let me know if you still find it useful!
